server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # Envoyer un battement de cœur toutes les 5 secondes
    lease-expiration-duration-in-seconds: 10 # Expire si aucune communication n'est reçue pendant 10 secondes
leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&heiMa% # La clé de vérification de connexion
    pubKeyPath: E:\leyou.test\prefile\tmp\rsa\rsa.pub # Adresse de clé publique
    priKeyPath: E:\leyou.test\prefile\tmp\rsa\rsa.pri # Adresse de clé privée
    expire: 30 # Temps d'expiration, en minutes
    cookieName: LY_TOKEN