server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.88.103:9300
  rabbitmq:
    host: 192.168.88.103
    virtual-host: /leyou
    username: leyou
    password: leyou
  jackson:
    default-property-inclusion: non_null #Configurer l'ignorance des valeurs nulles lors de la manipulation du résultat JSON
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka