server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.88.103
    username: leyou
    password: leyou
    virtual-host: /leyou
leyou:
  sms:
    accessKeyId:
    accessKeySecret:
    signName: 乐优商城
    verifyCodeTemplate: